### ISSUE TITLE
Add more foundational files on first go

### ISSUE THREAD

**Issue by BrianaCamp** [fictivekin/fk-sass#7]
A pain point I'm currently having is getting a project setup and running quickly with general base styles that always need to be updated per project. Such as fonts, spacing, colors, etc. 

I think what could cut down time and get someone up and running more quickly is to add the folder
- `_1_base`
  - `properties` 
  - `_spacing`, `_colors`, `_fonts`
  
Exactly like what we did for sweetgreen: https://github.com/fictivekin/sweetgreen-micro/tree/d0eba930eaa0fb46a82dda2fb938fbb9149a8878/_src/static/scss/_1_base 

I think maybe just commenting it all out and saying "update your font sizes and colors here" etc. So it's as simple as updating the values and seeing those changes right away. 

The same goes for the `config/_borders` file since that'll be another thing that's needed to change from project to project. 

The following files should also be added on initial setup since these values change from project to project:
- `config/_borders`
- `_links--m`
-

**Comment by jacobfentress** [comment]
closed this with the last commit, but neglected to reference the issue
